### ISSUE TITLE
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec()

### ISSUE THREAD

**Issue by lyx0124** [lyx0124/WMW#10]
Python: 3.7.4
OS: macOS Catalina 10.15.5

I installed all dependencies, loaded WMW into chrome, set BING_KEY the the Bing API key, and started the server successfully with `python3 run_server.py --parser_type h2t --finder_type bing`. Once I browsed a page, this error poped up (it did not crash the extension, just displayed this error in terminal and nothing happened to the sidebar):
```
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

**Comment by mdarcy220** [comment]
This seems like it could be related to the multiprocessing module in Python.  I've pushed a possible fix on the hotfix_10 branch.  Could you try that out and let me know if the error still occurs?  Also, could you post your Python and OS versions?

**Comment by mdarcy220** [comment]
Also, please post the exact command used to start the server and which page you visited to test.  Even for the working version, there are some pages that don't return any results.  One page known to return results in the working version is https://en.wikipedia.org/wiki/Penguin

**Comment by lyx0124** [comment]
hotfix_10 branch works now. One problem tho: I can't scroll through my search results. I can only see the first two results.

**Comment by mdarcy220** [comment]
Ok great. The non-scrolling thing is a known issue, although we don't have a ticket open for it (I'll add one in a moment).  From what I've seen, the issue you encountered is specific to OSX, and it is weird because in this case it seemed to happen when using a very normal/standard feature of Python's standard library.  At any rate, I'm glad the fix worked and I'll merge it to master.
